dist: xenial
language: node_js
node_js:
    - node
services:
    - docker
script:
    - docker-compose --version
    - docker-compose up -d smtp
    - ./demo/smtp-sink/wait-for-smtp.sh
    - docker logs smtp
    - docker-compose ps
    - cd demo/node
    - npm install
    - npm test
    - docker logs smtp
