dist: xenial
language: bash
services:
    - docker
script:
    - docker-compose --version
    - docker-compose up -d smtp
    - ./demo/smtp-sink/wait-for-smtp.sh
    - docker logs smtp
    - docker-compose ps
    - docker-compose run --rm ci
