dist: xenial
language: node_js
node_js:
    - node
services:
    - docker
before_script:
    - docker-compose up -d smtp
    - ./demo/smtp-sink/wait-for-smtp.sh
    - sudo chmod a+w demo/inbox
script:
    - cd demo/client
    - npm install
    - npm test
    - docker logs smtp
