version: '3'

services:
  
  smtp:
    build: smtp-sink
    image: smtp:ready
    container_name: smtp
    ports:
      - "25:25"
    volumes:
      - ./messages:/tmp

  ci:
    build: node
    image: node:ready
    container_name: node
    command: ./node/send.sh
