version: '3'

services:
  
  smtp:
    build: .
    image: smtp:ready
    container_name: smtp
    ports:
      - "25:25"
    volumes:
      - ./messages:/tmp

  bash:
    build: ./support/testing
    image: bash:alpine
    container_name: bash
    volumes:
      - .:/usr/local/src
