version: '3'

services:
  
  smtp:
    build: smtp-sink
    image: smtp:ready
    container_name: smtp
    ports:
      - "25:25"
    volumes:
      - ./messages:/tmp

  node:
    build: node
    image: node:ready
    container_name: node
    volumes:
      - .:/home/dev/app
    working_dir: /home/dev/app
