version: '3.7'

services:
  
  smtp:
    build: smtp-sink
    image: smtp:ready
    container_name: smtp
    ports:
      - "25:25"
    volumes:
      - ./messages:/tmp

  ci:
    build: 
      context: .
      dockerfile: ./node/Dockerfile
    image: node:ready
    container_name: node
    command: ./node/send.sh
