version: '3.7'

services:
  
  smtp:
    build: 
      context: ./demo
      dockerfile: ./smtp-sink/Dockerfile
    image: smtp:ready
    container_name: smtp
    ports: 
      - "5025:25"
    volumes:
      - ./demo/inbox:/tmp

  ci:
    build: 
      context: ./demo
      dockerfile: ./node/Dockerfile
    image: node:ready
    container_name: node
    command: ./node/send.sh
    volumes: 
      - ./demo/inbox:/usr/local/src/inbox
