version: '3.7'

services:
  
  smtp:
    build: 
      context: ./demo
      dockerfile: ./smtp-sink/Dockerfile
    image: smtp:ready
    container_name: smtp
    ports: 
      - "5025:25"
    volumes:
      - ./demo/inbox:/tmp
